apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  namespace: mongodb
spec:
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: singlenode-mongo-express
        image: mongo-express:0.45
        env:
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: mongoexpress
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: welcome
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            configMapKeyRef:
              name: mongodb-cfg
              key: MONGO-ROOT-USERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            configMapKeyRef:
              name: mongodb-cfg
              key: MONGO-ROOT-PASSWORD
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-cfg
              key: MONGO-SERVICE-HOST
        - name: ME_CONFIG_MONGODB_PORT
          valueFrom:
            configMapKeyRef:
              name: mongodb-cfg
              key: MONGO-SERVICE-PORT
        ports:
        - containerPort: 8081
          name: listener
      nodeSelector:
        mongodb-server: singlenode
