apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: mongodb
spec:
  selector:
    app: mongo-express
  ports:
  - name: mongo-express-listener
    protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 32018
  type: NodePort
