apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-cfg
  namespace: mongodb
data:
  MONGO-ROOT-USERNAME: root
  MONGO-ROOT-PASSWORD: welcome
  MONGO-SERVICE-HOST: mongodb-service.mongodb
  MONGO-SERVICE-PORT: "27017"
