apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb-listener
    protocol: TCP
    port: 27017
    targetPort: 27017
    nodePort: 32017
  type: NodePort
